### ISSUE TITLE
throw new TypeError("undefined is not an object (evaluating 'NSProcessInfo.processInfo.processName.toString')")

### ISSUE THREAD

**Issue by rustymagnet3000** [limneos/weak_classdump#9]
hi all,

I have been trying to dump the class information for two apps.  One app is a mix of Objective C and Swift and the other is pure Swift (2.0).  The jailbroken iPhone is o/s version 9.0.2.

When I run the:  cycript -p 1021 weak_classdump.cy; cycript -p 1021

I get the following error:
throw new TypeError("undefined is not an object (evaluating 'NSProcessInfo.processInfo.processName.toString')")

I can never attach to the process.  Any tips?  Sorry, if it is a basic question.  I am a first time user of weak_classdump.

**Comment by limneos** [comment]
Hello..

That’s because the new cycript version has some differences in the syntax. 

Although its fixable, I have another tool that should dump the class fine as it is, classdump-dyld

Check out https://github.com/limneos/classdump-dyld https://github.com/limneos/classdump-dyld 

You can also download a .deb from BigBoss repo.

I haven’t checked it out on Swift classes though, so let me know if the result needs any fixing.

Regards,

Limneos

**Comment by rustymagnet3000** [comment]
WOW!!!  Well done, @limneos .  It works brilliantly.  :)

One small note; do you know why C header files are not picked up?  It seems to have only picked up Objective-C header files.
